### ISSUE TITLE
wikia轉址提醒（選用）

### ISSUE THREAD

**Issue by s890081tonyhsu** [chrisliuqq/wiz-tw#2]
舊版API網址：http://zh.nekowiz.wikia.com/api.php
新版API網址：https://nekowiz.fandom.com/zh/api.php

由於wikia與fandom合作的關係，所以wiki的網址有做修改。

在wikia官方的轉址處理下，閣下的專案有透過HTTP 301轉址取得正確資料。

所以此Issue只具備告知作用，如果有要就麻煩你了。

**Comment by chrisliuqq** [comment]
收到唷，感謝告知，過兩天來調整。

**Comment by chrisliuqq** [comment]
已調整網址，待 github pages refresh 後觀察一下。

**Comment by chrisliuqq** [comment]
看起來似乎正常，而且好像比以前快很多很多（？）
暫時跑一陣子看看。

**Comment by chrisliuqq** [comment]
都跑了半年了，來關票囉。
