### ISSUE TITLE
網頁版隱藏版尾

### ISSUE THREAD

**Issue by a54081438** [chrisliuqq/wiz-tw#4]
網頁版是否也可以新增隱藏版尾按鈕
不然搜尋時題目一多，最後一題都會被擋住

**Comment by chrisliuqq** [comment]
沒想到還有人在用 XD

先簡單加上 padding bottom 讓往下滑之後最後一題不會被擋住。

這個專案有點久了… 我現在有點難架出之前的環境來編 coffee script… 這年頭沒人在用了吧…

要的話應該就是用 vue3 + tailwind css 重寫… 不過我自己都沒在玩黑貓了 XD 這工具這麼久還能動我也滿意外的…

**Comment by chrisliuqq** [comment]
看起來後續應該沒有繼續回報了，先 close 囉
